name: Run mmain.py on trans.yaml changes

on:
  push:
    paths:
      - trans.yaml

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pyyaml
          pip install python-dotenv
      - name: Run mmain.py
        run: python mmain.py
