name: Run mmain.py on trans.yaml changes

on:
  push:
    paths:
      - trans.yaml

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Run mmain.py
        run: python mmain.py
